phonebook:menu.o print.o addrecord.o deleterecord.o getdata.o searchrecord.o saverecord.o get.o editdata.o
	cc menu.o print.o addrecord.o deleterecord.o getdata.o searchrecord.o saverecord.o get.o editdata.o -o phonebook
menu.o:menu.c
	cc -c menu.c
print.o:print.c
	cc -c print.c
addrecord.o:addrecord.c
	cc -c addrecord.c
deleterecord.o:deleterecord.c
	cc -c deleterecord.c
getdata.o:getdata.c
	cc -c getdata.c
searchrecord.o:searchrecord.c
	cc -c searchrecord.c
saverecord.o:saverecord.c
	cc -c saverecord.c
get.o:get.c
	cc -c get.c
editdata.o:editdata.c
	cc -c editdata.c
